### ISSUE TITLE
Disk slot assignments dont save properly

### ISSUE THREAD

**Issue by azzuron** [olehj/disklocation#67]
Not sure what im facing here. I tried to set the drive slots and i screwed it up because i assigned the slots then changed the orientation, i deleted the sqllite database as per notes on doing a factory reset of the plugin i found. That looked to work, i had a blank slate. i configured the layout first saved it. then i went through and di the locate and slot assignments. when i saved it, most of the drives were not actually assigned to the proper slots, and many where not saved at all. So i reset it again and tried to just assign a few at a time. and they didnt assign right.

example, first two slots are empty next two are parity disks. i assigned my parity disks to the 2nd two slots and saved.

the Top row of the layout showed the first slot and the 3rd slot as having disks, but numbered them 3 and 4, then the two empty slots on the row were also numbered 3 and 4. Something seems broken. Or my understanding of how to use this is wrong. :)

Thanks.

**Comment by olehj** [comment]
I tried to put myself in your position, so I made some modifications now which might help you.

When the location database is empty, the tray location for the top table are now disabled. You do not need to specify which is empty at a new table, only when you move disks after the table is saved.

The orientation and all other settings works as expected and there's no real reason to save the table before you add drives to the table, not other than getting the overview of how it looks like (so it is not a bad practice anyway). The only thing that can mess up the tray assignments happens when empty tray and a slotted tray manage to get the same tray number. I am pretty sure I implemented this for the already stored databases, but it might have glitched away from the unassigned drives which is why they are now disabled. Just tag the drives to the position and save it, nevermind the empty slot, they should get figured automagically. 

Please update to 2019.05.02 version, delete the sqlite-file and try again.
